#ifndef __HWDOUT_TRANSFORM_H__
#define __HWDOUT_TRANSFORM_H__

#include <glib-object.h>
#include <wayland-client.h>

G_BEGIN_DECLS

typedef enum {
    HWDOUT_TRANSFORM_NORMAL = WL_OUTPUT_TRANSFORM_NORMAL,
    HWDOUT_TRANSFORM_90 = WL_OUTPUT_TRANSFORM_90,
    HWDOUT_TRANSFORM_180 = WL_OUTPUT_TRANSFORM_180,
    HWDOUT_TRANSFORM_270 = WL_OUTPUT_TRANSFORM_270,
    HWDOUT_TRANSFORM_FLIPPED = WL_OUTPUT_TRANSFORM_FLIPPED,
    HWDOUT_TRANSFORM_FLIPPED_90 = WL_OUTPUT_TRANSFORM_FLIPPED_90,
    HWDOUT_TRANSFORM_FLIPPED_180 = WL_OUTPUT_TRANSFORM_FLIPPED_180,
    HWDOUT_TRANSFORM_FLIPPED_270 = WL_OUTPUT_TRANSFORM_FLIPPED_270,
} HwdoutTransform;

#define HWDOUT_TYPE_TRANSFORM (hwdout_transform_get_type())
GType
hwdout_transform_get_type(void);

G_END_DECLS

#endif /* __HWDOUT_TRANSFORM_H__ */
